# Generated by Django 5.1.3 on 2024-11-27 13:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='follows',
            field=models.ManyToManyField(related_name='user_follows', to=settings.AUTH_USER_MODEL),
        ),
    ]
