# Generated by Django 5.1.3 on 2024-12-01 08:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='preview',
            field=models.FileField(upload_to='previews', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv', 'png', 'jpg', 'jpeg'])]),
        ),
    ]
